"""Mock/cached mode for distressed credit agent demonstrations.

This module provides pre-cached agent responses for instant demonstrations
without requiring LLM API keys. This is essential for smooth interview demos.

Usage:
    from examples.distressed.mock_mode import MockCreditCommittee
    mock = MockCreditCommittee()
    result = mock.run_ati_analysis()
    print(result.rendered_memo())
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime

from examples.distressed.agents import (
    AgentBrief,
    CreditCommitteeResult,
)
from examples.distressed.ati_2023 import build_ati_situation

logger = logging.getLogger(__name__)


@dataclass
class MockAgentBrief:
    """Mock agent brief for demonstration."""

    agent_name: str
    content: str
    tokens_used: int = 0
    tool_calls_made: list[str] = field(default_factory=list)


class MockCreditCommittee:
    """Mock credit committee with pre-cached responses.

    This enables instant demonstrations without API calls, ideal for:
    - Interview presentations
    - Code reviews
    - Testing without token costs
    - Reproducible outputs
    """

    def __init__(self, use_mock: bool = True):
        """Initialize mock committee.

        Args:
            use_mock: If True, use cached responses. If False, run live agents.
        """
        self.use_mock = use_mock

    def run_ati_analysis(self) -> CreditCommitteeResult:
        """Run the ATI Physical Therapy analysis with mock or live agents.

        Returns:
            CreditCommitteeResult with full analysis
        """
        if self.use_mock:
            logger.info("Running ATI analysis in MOCK mode (no API calls)")
            return self._get_mock_ati_result()
        else:
            logger.info("Running ATI analysis in LIVE mode (requires API key)")
            from examples.distressed.agents import run_credit_committee
            import asyncio

            situation = build_ati_situation()
            return asyncio.run(run_credit_committee(situation))

    def _get_mock_ati_result(self) -> CreditCommitteeResult:
        """Get pre-cached ATI analysis result.

        This is the exact output that would be generated by live agents,
        based on the actual memo in ati_2023_memo.md.
        """
        situation = build_ati_situation()

        # Mock CapStructureAgent brief
        cap_brief = MockAgentBrief(
            agent_name="CapStructureAgent",
            content="""LEVERAGE: $550M gross debt / $6.7M FY22 EBITDA = **82.1x** (pre-restructuring). Post-TSA: $450M 1L + $125M new 2L = $575M on unchanged TTM EBITDA = **85.8x**. Both measurements are functionally meaningless — this is a cap-stack-in-distress, not a going-concern levered business. The question is what EBITDA does forward, not backward.

COVERAGE: LTM EBITDA / cash interest. Cash interest pre-TSA at ~SOFR+725 on $500M 1L ≈ **$61M**; LTM EBITDA $6.7M → **0.11x coverage**. Broken by any definition. Post-TSA: 1L cash interest falls to ~$49M (on reduced $400M 1L principal), 2L is PIK so no cash interest; total cash interest **~$49M** vs FY23 guided EBITDA of $25-35M → coverage improves to **0.5-0.7x**. Still negative free cash flow but survivable if revolver capacity holds.

FULCRUM: **The new 2L PIK Convertible is the fulcrum security by design.** It sits senior to $165M of Series A Preferred and junior to $450M of 1L debt. In any re-distress scenario, 2L converts to majority of reorganized equity (standard Chapter 11 cramdown mechanics). HPS controls the 1L and would be the natural senior creditor in any Chapter 11; 2L participant group controls what comes out the other side. This is the correct layer for a loan-to-own thesis.

RECOVERY ANALYSIS:
- Base case ($30M EBITDA by FY2024): PT wage inflation normalizes per BLS trajectory. Company trades to ~7x EBITDA = $210M enterprise value at exit. 1L recovers at par; 2L converts to ~80% of post-reorg equity = ~$150M on $125M face (accreted to ~$145M by conversion) → **~105c par recovery** on a 30-month hold.
- Bear case ($10-15M EBITDA): Sector wage pressure persists; re-enters Chapter 11 in late 2024. Liquidation / going-concern sale at distressed multiple (~5x trough EBITDA = $60M EV). 1L takes $400M face against $60M value → ~15c par. 2L takes control of residual equity via cramdown; residual value after 1L claim ≈ $0, but 2L owns post-reorg equity on a re-emergence plan → **~55-70c par recovery** (highly scenario-dependent; meaningful impairment but not zero).
- Bull case ($50M+ EBITDA by FY2025): Sector consolidation thesis plays out. Strategic buyer (Select Medical, Athletico, or a PE roll-up platform) pays 11-13x EBITDA = $550-650M. 1L recovers at par; 2L converts at favorable valuation → **~250-320c par recovery** on a 24-36 month hold. This is the realized scenario (August 2025 take-private closed at $523.3M TEV, ~11.2x LTM Adj EBITDA).

ASSET COVERAGE: Outpatient PT is asset-light — leased clinics, intangible clinician relationships, modest PP&E ($65M at Q4'22). Tangible asset coverage of the $450M 1L is approximately **14%**. This is emphatically **not** an asset-backed recovery thesis; it is a cash-flow / going-concern / optionality thesis. The Workers' Compensation franchise (legacy since 1996) is the only quasi-asset — sticky payor relationships in IL/TX/PA — but not collateralizable.

BEST RISK/REWARD TRANCHE: **The new 2L PIK Convertible** — not even close. The 1L is already owned by HPS at par and returns are capped by rate spread. The Series A Preferred sits below the new 2L and has no conversion optionality against the true operating recovery. The 2L is the only tranche where investor underwrites outcome (wage normalization) and captures majority of upside.

SUMMARY: The post-TSA cap stack is structurally unsustainable without EBITDA recovery, but the PIK coupon on 2L converts the coverage problem from a cash problem into an accretion problem — buying 18-24 months of runway. The 2L PIK Convertible is correctly-sized entry into an 86x-leveraged stack with a visible catalyst path.""",
            tokens_used=1500,
            tool_calls_made=[
                "calculate_leverage",
                "calculate_coverage",
                "analyze_recovery_scenarios",
            ],
        )

        # Mock SituationAgent brief
        sit_brief = MockAgentBrief(
            agent_name="SituationAgent",
            content="""KEY STRUCTURAL EVENTS:
- **2022 EBITDA collapse (-83%)** from $39.8M → $6.7M — driven by PT wage inflation and therapist attrition, not demand destruction. Clinic visit volumes held; company simply couldn't staff enough therapists to capture them. This is a **supply-side** problem, which has a different (faster) resolution path than a demand-side thesis.
- **Feb 2022 HPS-led $550M refinancing** baked in aggressive leverage assumptions (~14x trailing, priced for continued COVID-era margin). When FY2022 margin compressed, covenants broke immediately — this is not a secular decline story, it is a refinancing that was mispriced 12 months earlier.
- **April 2023 TSA is a lender-friendly restructuring** engineered by HPS and prospective 2L participants. It preserves first-lien seniority for HPS, exchanges $100M of that 1L into 2L PIK convertible (de-leveraging cash-pay stack without impairing secured rights), and adds $25M of new money. Existing equity is not wiped — 1:50 reverse split preserves NYSE listing. This structure signals that **the senior creditors believe in going concern**.

UPCOMING CATALYSTS:
- **Q2 2023 earnings (expected Aug 2023)** — first look at whether EBITDA run-rate exits single-digits. Even a $15M quarterly run-rate validates the supply-side recovery thesis.
- **Reverse stock split effective June 14, 2023** — administrative, but maintains NYSE listing compliance.
- **BLS PT wage growth data (monthly)** — macro input. Q1 2023 prints already show deceleration; continuation through Q2-Q3 is the primary thesis validation.
- **Q3/Q4 2023 EBITDA prints** — 2-quarter window to re-rate. If EBITDA confirms $25-30M run-rate, paper trades to 90c+ and optionality rises; if it confirms sub-$15M, second distress event likely and we exercise fulcrum conversion.
- **Sector M&A activity** — Select Medical, Athletico, and US Physical Therapy consolidation signaling improves exit optionality.

NOISE: SPAC-era securities class action (FVAC II / 2021 de-SPAC disclosures) — expected to be resolved under D&O insurance and sponsor indemnities. Will distract management but should not impair post-TSA capital. **FLAG: at TSA signing this is unresolved; settled for $31M in Sep 2024.**

INFORMATION GAPS:
- Workers' comp reimbursement trend by state (IL, TX, PA concentration) — only publicly disclosed at aggregate level.
- Monthly same-clinic visit volume — reported quarterly only; PT recovery is a monthly signal.
- Exact 2L PIK convertible terms: conversion price, change-of-control premium, anti-dilution formula — must be verified against final indenture, not TSA summary.
- Advent International's behavior on Series A Preferred in any future restructuring — historically supportive but not guaranteed.

SUMMARY: Supply-side (PT labor) problem in a structurally growing sector ($53B market, fragmented); entry is being offered at peak stress and is visibly catalyzed by dateable EBITDA prints. This is a classic "EBITDA recovery trade" — 2-3 quarters of data will vindicate or invalidate the thesis with high information density.""",
            tokens_used=1200,
            tool_calls_made=[],
        )

        # Mock CreditRiskAgent brief
        risk_brief = MockAgentBrief(
            agent_name="CreditRiskAgent",
            content="""VERDICT: PROCEED WITH CAUTION
RISK RATING: 4 (high)

CHALLENGES TO RECOVERY MATH:
- The base case ($30M EBITDA by FY24) assumes linear wage normalization. Real PT wage data is regional and noisy — a 2-quarter delay would trigger either a covenant amendment request or re-entry to formal restructuring. The cap-structure brief's "105c par" base-case recovery assumes a clean conversion path; more realistically, a 6-month delay compounds PIK accretion but also compounds senior interest, eroding the equity value we would own.
- "Equity-conversion upside" assumes we get to convert at participant-favorable valuations. In practice, HPS (senior) has leverage to force a sale at a level where 2L recovery is capped (they only need par + cash interest to be whole). If HPS's senior cash needs force a sale at $350M EV in late 2024, 2L recovery would be closer to 60-70c par, not 105.
- PIK-convertible-to-equity transitions are **slow in mark-to-market terms**. Audit committees holding this paper will mark at book value minus a 15-25% haircut for 18-24 months even if credit improves. The return profile looks lumpy on realized-return basis but has stale NAV volatility for any IRR-sensitive LP.

TAIL RISKS:
- **CMS reimbursement cut**: Medicare Physician Fee Schedule review every 3 years. The 2024 cycle proposed a ~3.4% cut to PT codes before partial reversal. A steeper cut would compress EBITDA by $5-8M — enough to break the recovery thesis.
- **Illinois Workers' Comp reform** — ATI's largest state exposure, and IL workers' comp is under periodic legislative scrutiny. A structural change to fee schedules or authorization rules would disproportionately hit ATI's margin-accretive segment.
- **Competitive consolidation from above**: Select Medical or UnitedHealth/Optum acquires a distressed peer (USPH, Professional PT) at a lower multiple before ATI's recovery is complete — tightens M&A exit multiples.
- **SPAC litigation settlement exceeds $50M** with insufficient D&O coverage — impairs junior capital including our 2L.

LEGAL / PROCESS RISKS:
- TSA is **out-of-court**, which means no 363-sale protection for assets and no Bankruptcy Code stay if creditors defect. If Q3 2023 shows deterioration, a Chapter 11 filing re-opens the entire cap stack — our 2L PIK becomes a pre-petition claim subject to valuation fights and cramdown process.
- HPS's 1L has roughly 85-90% coverage under going-concern value assumptions. In a foreclosure scenario they can credit-bid; our 2L recovery in that path depends entirely on cramdown equity value (see bear case above).
- Appraisal-rights risk in any future take-private: minority shareholders can force valuation litigation. (Note: ultimately arose August 2025 in minimal form — short-form merger squeezed out ~1.4% minority; appraisal exposure was bounded.)

EXIT LIQUIDITY: Three paths:
1. **PIK converts to equity on re-distress event** → we hold majority post-reorg equity → M&A exit to strategic (Select Medical, Athletico) — this is the base path for distressed credit and played out in Aug 2025.
2. **Whole-company sale without conversion** (Select Medical / UnitedHealth/Optum pays par+) → cleaner, faster, less likely given HPS's own incentives.
3. **Secondary market for 2L PIK paper** — illiquid, 1-2 dealers, 3-5 point bid/ask. Effectively mark-to-matrix until a catalyst.

Primary risk: M&A market for outpatient PT chains cooled meaningfully from 2021 peak. 2023-2024 M&A activity will be thinner than the thesis assumes; exit timing is a real concern.

SUMMARY: The trade has real merit and structure is well-designed, but recovery math glosses over execution timing and HPS's divergent senior incentives. Size as a meaningful-but-bounded position. If Q3 2023 EBITDA print (November 2023) does not confirm $25M+ run-rate, reassess; do not add.""",
            tokens_used=1800,
            tool_calls_made=["check_covenant_headroom", "calculate_leverage"],
        )

        # Mock CreditCommitteeAgent brief
        committee_brief = MockAgentBrief(
            agent_name="CreditCommitteeAgent",
            content="""RECOMMENDATION: BUY
INSTRUMENT: 2L PIK Convertible Notes (April 2023 TSA, 8% PIK, Aug 2028 maturity, fulcrum conversion into post-reorg equity). Target up to 20% of $25M new-money allocation and up to 15% of $100M 1L-to-2L exchange volume.
SIZING: 1.0-1.5% of AUM initial ($12-18M on a $1.2B fund basis). Scale to 2.0% if Q3'23 EBITDA print (November 2023) confirms $25M+ quarterly run-rate. Hard cap at 2.0%.
TARGET PRICE: 140-180c par base-case return on 24-36 month hold; 250-320c par bull case; 55-70c par bear case.
CATALYST: Q2/Q3 2023 EBITDA prints confirming PT wage cost stabilization. BLS PT wage data already showing deceleration through Q1 2023.

## Executive Summary
ATI Physical Therapy is a top-5 US outpatient PT platform (~900 clinics, 24 states) in a $53B fragmented market. FY22 EBITDA collapsed 83% (to $6.7M) on a **supply-side** shock — PT wage inflation and therapist attrition — not demand destruction. The April 2023 TSA creates a new 2L PIK convertible ($25M new money + $100M 1L-to-2L exchange, 8% PIK, Aug 2028 maturity) that is engineered to be the fulcrum security. We should participate: instrument gives us asymmetric upside on PT wage normalization (which BLS data already shows beginning) and downside protection via fulcrum-conversion into majority of post-reorg equity if situation re-distresses. Asset coverage is thin (asset-light operating model), so this is explicitly a cash-flow / going-concern / optionality trade, not an asset-backed one — and our sizing reflects that.

## Thesis
- **Supply-side shocks resolve faster than demand-side shocks.** PT clinic visit demand is secular; 2022 EBITDA collapse was labor inability to capture demand. BLS Q1 2023 already shows PT wage growth decelerating. Base case EBITDA recovery to $25-35M by FY24 is measurable within 2-3 quarterly prints.
- **The instrument is a fulcrum by design.** HPS and prospective 2L participant group engineered the TSA to own equity if Q2-Q4 2023 disappoints. This is loan-to-own from day one — downside is controlled by the same structure that delivers upside.
- **Workers' comp franchise is an underappreciated margin differentiator.** ATI's workers' comp business (legacy since 1996, concentrated in IL/TX/PA) delivers structurally higher margin than pure-play PT competitors. Public-side sell-side coverage treats it as undifferentiated — this is an information-edge source for our underwriting.
- **Sector consolidation optionality is free.** Top-6 chains are ~10% of US PT clinics. Post-restructuring ATI, with our capital, becomes a consolidator in a market where every smaller operator is facing the same wage pressure. This roll-up optionality has real value in base and bull cases and costs us nothing at underwriting.

## Downside
Bear case recovery is 55-70c per dollar on our 2L face (see cap-structure and risk briefs). On a 1.5% AUM position ($18M on $1.2B fund), the capital at risk is **45-80 bps of fund NAV** in a realistic bear scenario. This is consistent with our capital-preservation philosophy: if the thesis is wrong (PT wages don't normalize by Q3 2023, CMS cuts reimbursement, or IL workers' comp reform hits), we absorb a bounded, non-catastrophic loss. Structural protection: (i) PIK coupon converts coverage shortfall into an accretion problem, buying 18-24 months of runway; (ii) fulcrum-conversion mechanics give us majority control in any downside restructuring; (iii) 1L-to-2L exchange reduces our structurally senior pari-passu debt by $100M from day one — a meaningful de-risking event baked into the TSA itself.

## Sizing Rationale
Initial 1.0-1.5% AUM reflects high conviction on the supply-side thesis, medium conviction on execution timing. Scale to 2.0% if Q3 2023 print (Nov 2023) confirms $25M+ quarterly EBITDA run-rate. Hard cap at 2.0% — this is an illiquid, junior, single-issuer trade and portfolio theory demands bounded concentration even at high conviction. Optional hedge: 25%-sized short in USPH (US Physical Therapy, $500M cap, liquid pure-play comp) as insurance against a sector-wide PT wage shock. Not required in base case; activate if Q2 2023 print suggests wage pressure persisting.

## Vote
**APPROVE WITH CONDITIONS.** Conditions: (1) final 2L PIK indenture terms match TSA summary on conversion price, change-of-control premium, and anti-dilution protection — legal review before funding; (2) independent valuation of asset coverage to confirm no hidden secured claims ahead of 1L; (3) initial allocation capped at 1.0% AUM until Q2 2023 EBITDA print, with pre-approved scale-up authority to 1.5% on an in-line print and 2.0% on an above-range print.""",
            tokens_used=2000,
            tool_calls_made=[],
        )

        total_tokens = (
            cap_brief.tokens_used
            + sit_brief.tokens_used
            + risk_brief.tokens_used
            + committee_brief.tokens_used
        )

        return CreditCommitteeResult(
            situation=situation,
            cap_structure_brief=AgentBrief(
                agent_name=cap_brief.agent_name,
                content=cap_brief.content,
                tokens_used=cap_brief.tokens_used,
                tool_calls_made=cap_brief.tool_calls_made,
            ),
            situation_brief=AgentBrief(
                agent_name=sit_brief.agent_name,
                content=sit_brief.content,
                tokens_used=sit_brief.tokens_used,
                tool_calls_made=sit_brief.tool_calls_made,
            ),
            credit_risk_brief=AgentBrief(
                agent_name=risk_brief.agent_name,
                content=risk_brief.content,
                tokens_used=risk_brief.tokens_used,
                tool_calls_made=risk_brief.tool_calls_made,
            ),
            committee_memo=AgentBrief(
                agent_name=committee_brief.agent_name,
                content=committee_brief.content,
                tokens_used=committee_brief.tokens_used,
                tool_calls_made=committee_brief.tool_calls_made,
            ),
            total_tokens=total_tokens,
        )

    def run_equity_analysis(self, ticker: str = "AAPL") -> dict:
        """Run equity agent analysis with mock or live agents.

        Args:
            ticker: Stock ticker symbol

        Returns:
            Dictionary with analysis results
        """
        if self.use_mock:
            logger.info(f"Running equity analysis for {ticker} in MOCK mode")
            return self._get_mock_equity_result(ticker)
        else:
            logger.info(f"Running equity analysis for {ticker} in LIVE mode")
            from src.agents.orchestrator import run_full_analysis
            import asyncio

            result = asyncio.run(run_full_analysis(ticker))
            return {
                "ticker": ticker,
                "decision": result.get("decision", "HOLD"),
                "confidence": result.get("confidence", 0.5),
                "reasoning": result.get("reasoning", ""),
                "total_tokens": result.get("total_tokens", 0),
            }

    def _get_mock_equity_result(self, ticker: str) -> dict:
        """Get pre-cached equity analysis result.

        Args:
            ticker: Stock ticker symbol

        Returns:
            Dictionary with mock analysis results
        """
        # Mock QuantAgent brief
        quant_brief = """SIGNAL: BUY (probability 0.68)
CONFIDENCE: 68%

TECHNICAL INDICATORS:
- RSI(14): 42.3 (approaching oversold territory)
- MACD(12,26,9): Bullish crossover confirmed
- Bollinger Bands(20,2): Price near upper band, momentum positive
- Volume: 1.2x average, confirming institutional interest

FEATURE IMPORTANCE (Top 5 SHAP):
1. momentum_20: +0.32 (strong positive momentum)
2. rsi_14: +0.28 (oversold bounce potential)
3. volatility_10: +0.19 (elevated volatility supports breakout)
4. volume_ratio: +0.15 (high volume confirms conviction)
5. macd_signal: +0.12 (momentum alignment)

SUMMARY: Technical indicators show bullish setup with strong momentum (momentum_20: +0.32) and oversold RSI conditions (42.3) suggesting a bounce. Volume is elevated (1.2x average) indicating institutional participation. The ensemble model predicts up with 68% confidence, aligning with technical setup."""

        # Mock NewsAgent brief
        news_brief = """SENTIMENT: Positive

RECENT HEADLINES (Last 10):
1. "Company beats Q3 earnings expectations, revenue up 8% YoY"
2. "New product launch exceeds analyst projections"
3. "Major competitor announces supply chain issues, potential market share gain"
4. "CEO announces strategic partnership with industry leader"
5. "Analyst upgrades from 2 firms, price target raised 15%"
6. "Company announces $2B share repurchase program"
7. "Regulatory approval for key product line obtained"
8. "Institutional investor increases stake to 8.5%"
9. "Company expands into new geographic market"
10. "Industry report shows favorable macro conditions"

SEC FILINGS (Last 5):
1. 10-Q filed: Revenue growth of 15% YoY, margin expansion
2. 8-K filed: Material contract win worth $500M
3. DEF 14A filed: Director appointments with strong credentials
4. 10-K filed: Strong balance sheet, cash position improved
5. 8-K filed: No material adverse events disclosed

KEY INFORMATION GAPS:
- No recent guidance on Q4 outlook
- Competitive pricing data incomplete
- Regulatory timeline for pending approvals unclear

SUMMARY: News flow is overwhelmingly positive with 8/10 recent headlines being favorable. SEC filings show strong fundamentals with revenue growth, margin expansion, and no material adverse events. Sentiment analysis confirms positive outlook. The combination of strong technical setup and positive news flow supports a BUY recommendation."""

        # Mock RiskAgent brief
        risk_brief = """VERDICT: PROCEED WITH CAUTION
RISK RATING: 2 (low)

KEY RISKS IDENTIFIED:
1. **Market Volatility**: VIX at 18.5 (elevated) — could trigger sudden reversal
2. **Concentration Risk**: 45% of portfolio in single position — exceeds typical 20% limit
3. **Earnings Risk**: Q4 earnings in 2 weeks — guidance miss could cause 15% drawdown
4. **Liquidity Risk**: Average daily volume $800M — position size $45M represents 5.6% of daily volume, exit risk elevated
5. **Macro Risk**: Fed meeting next week — hawkish surprise could pressure rates

HEDGING RECOMMENDATIONS:
- Consider reducing position size to 20% of portfolio
- Implement trailing stop-loss at 5% below entry
- Hedge with VIX calls if volatility persists

SUMMARY: While technical and fundamental signals are positive, elevated market volatility and concentration risk warrant caution. Recommend proceeding with reduced position size and protective stops in place."""

        # Mock PortfolioManagerAgent brief
        pm_brief = """DECISION: BUY
CONFIDENCE: 72%

REASONING:
- QuantAgent shows strong technical setup with 68% model confidence and bullish momentum indicators
- NewsAgent confirms positive news flow with 8/10 favorable headlines and strong SEC filings
- RiskAgent identifies elevated volatility and concentration concerns but recommends proceeding with hedges
- Weighted assessment: Strong technical and fundamental signals outweigh moderate risk concerns

KEY RISK TO MONITOR:
- Market volatility (VIX at 18.5) — primary risk factor
- Q4 earnings announcement in 2 weeks — catalyst validation point

SUMMARY: BUY recommendation with 72% confidence based on strong technical indicators, positive news flow, and solid fundamentals. Risk factors identified (volatility, concentration) warrant position sizing at 20% of portfolio rather than 45%. Implement protective stops and monitor VIX levels."""

        total_tokens = 1500 + 1200 + 1800 + 1500  # Estimated tokens

        return {
            "ticker": ticker,
            "quant_brief": quant_brief,
            "news_brief": news_brief,
            "risk_brief": risk_brief,
            "pm_brief": pm_brief,
            "decision": "BUY",
            "confidence": 0.72,
            "total_tokens": total_tokens,
            "mode": "MOCK" if self.use_mock else "LIVE",
        }


def run_demo(showcase: bool = True) -> None:
    """Run the demonstration showcase.

    This function runs both distressed credit and equity analyses
    in mock mode and prints the results.

    Args:
        showcase: If True, print formatted output. If False, return results.
    """
    print("\n" + "=" * 80)
    print("QUANTAI DASHBOARD - DEMONSTRATION SHOWCASE")
    print("=" * 80)
    print("\nMode: MOCK (no API key required)")
    print(f"Timestamp: {datetime.now().isoformat()}")
    print("\n" + "-" * 80)

    # Run ATI distressed credit analysis
    print("\n1. DISTRESSED CREDIT ANALYSIS - ATI PHYSICAL THERAPY")
    print("-" * 80)
    mock = MockCreditCommittee(use_mock=True)
    result = mock.run_ati_analysis()

    print(f"\nTotal LLM Tokens Used: {result.total_tokens:,}")
    print(f"\nCapStructureAgent: {result.cap_structure_brief.tokens_used:,} tokens")
    print(f"SituationAgent: {result.situation_brief.tokens_used:,} tokens")
    print(f"CreditRiskAgent: {result.credit_risk_brief.tokens_used:,} tokens")
    print(f"CreditCommitteeAgent: {result.committee_memo.tokens_used:,} tokens")

    # Print brief excerpts
    print("\n--- CAP STRUCTURE BRIEF EXCERPT ---")
    print(result.cap_structure_brief.content[:500] + "...")

    print("\n--- COMMITTEE RECOMMENDATION ---")
    lines = result.committee_memo.content.split("\n")
    for i, line in enumerate(lines[:15]):  # Show first 15 lines
        print(line)

    # Run equity analysis
    print("\n" + "-" * 80)
    print("\n2. EQUITY ANALYSIS - AAPL")
    print("-" * 80)
    equity_result = mock.run_equity_analysis("AAPL")

    print(f"\nTotal Tokens: {equity_result['total_tokens']:,}")
    print(f"\nDecision: {equity_result['decision']}")
    print(f"Confidence: {equity_result['confidence']:.0%}")

    print("\n--- PORTFOLIO MANAGER DECISION ---")
    print(equity_result["pm_brief"])

    print("\n" + "=" * 80)
    print("DEMONSTRATION COMPLETE")
    print("=" * 80)
    print("\nTo run live mode (requires API key):")
    print("  mock = MockCreditCommittee(use_mock=False)")
    print("  mock.run_ati_analysis()")
    print("\nTo run equity analysis live:")
    print("  mock.run_equity_analysis('AAPL')")
    print()


if __name__ == "__main__":
    run_demo()
