"""initial schema with ohlcv features trades portfolio backtest tables

Revision ID: 472b89c33366
Revises: 
Create Date: 2026-03-27 22:10:07.495987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472b89c33366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=True),
    sa.Column('final_value', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('bb_pct_b', sa.Float(), nullable=True),
    sa.Column('bb_bandwidth', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('stoch_k', sa.Float(), nullable=True),
    sa.Column('stoch_d', sa.Float(), nullable=True),
    sa.Column('adx_14', sa.Float(), nullable=True),
    sa.Column('close_to_sma50', sa.Float(), nullable=True),
    sa.Column('close_to_sma200', sa.Float(), nullable=True),
    sa.Column('sma50_to_sma200', sa.Float(), nullable=True),
    sa.Column('return_lag_1', sa.Float(), nullable=True),
    sa.Column('return_lag_2', sa.Float(), nullable=True),
    sa.Column('return_lag_3', sa.Float(), nullable=True),
    sa.Column('return_lag_5', sa.Float(), nullable=True),
    sa.Column('volatility_5', sa.Float(), nullable=True),
    sa.Column('volatility_20', sa.Float(), nullable=True),
    sa.Column('momentum_5', sa.Float(), nullable=True),
    sa.Column('momentum_20', sa.Float(), nullable=True),
    sa.Column('mean_reversion_20', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ohlcv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('positions_value', sa.Float(), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('cumulative_return', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('portfolio_snapshots')
    op.drop_table('ohlcv')
    op.drop_table('features')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
